### ISSUE TITLE
口罩预约

### ISSUE THREAD

**Issue by Yeaahenan** [xiaopengyaa/node-mask-appointment#1]
经纬度一定需要在当地才可以实现吗，我通过经纬度定位预约反馈附近4公里无药店

**Comment by xiaopengyaa** [comment]
当选择到店自取的时候，经纬度是必填的，反馈无药店是因为你所定位的地址附近没有守护港城小程序所关联到的药店。解决办法有两个：1、重新选择一个新的经纬度；2、预约类型选择为邮寄

**Comment by xiaopengyaa** [comment]
> 经纬度一定需要在当地才可以实现吗，我通过经纬度定位预约反馈附近4公里无药店

当选择到店自取的时候，经纬度是必填的，反馈无药店是因为你所定位的地址附近没有守护港城小程序所关联到的药店。解决办法有两个：1、重新选择一个新的经纬度；2、预约类型选择为邮寄

**Comment by Yeaahenan** [comment]
我的公网ip并不是预约所在地，经纬定位附近是有关联守护港城的药店，我选择自取和邮寄都不成功，是否需要预约所在地的公网ip才可以实现，

**Comment by xiaopengyaa** [comment]
> 我的公网ip并不是预约所在地，经纬定位附近是有关联守护港城的药店，我选择自取和邮寄都不成功，是否需要预约所在地的公网ip才可以实现，

当时我测试的时候也不是在当地，也是没问题的。你选择邮寄的时候不成功，提示的是什么信息？

**Comment by Yeaahenan** [comment]
已经预约成功且有预约记录，谢谢！解决燃眉之急
