### ISSUE TITLE
预约成功但预约记录为空

### ISSUE THREAD

**Issue by Drac4ry** [xiaopengyaa/node-mask-appointment#2]
预约到两次了，一次选的邮寄一次选上门，程序显示预约成功，但是隔了几个小时再看小程序的预约记录都是空。
但！是！再次预约程序就会通知我已预约过，下次可以预约时间为...
这是咋回事呀大佬

**Comment by xiaopengyaa** [comment]
> 预约到两次了，一次选的邮寄一次选上门，程序显示预约成功，但是隔了几个小时再看小程序的预约记录都是空。
> 但！是！再次预约程序就会通知我已预约过，下次可以预约时间为...
> 这是咋回事呀大佬

你的openId是自己获取的吗？

**Comment by Drac4ry** [comment]
对的，我在公众号平台那里获取的我自己openid，两个账号都试过了

**Comment by xiaopengyaa** [comment]
> 对的，我在公众号平台那里获取的我自己openid，两个账号都试过了

在哪个微信号里的小程序获取到的openId，应该都会在对应的微信号里看到预约信息。你所说的公众号平台获取是指？

**Comment by Drac4ry** [comment]
百度看的教程，在公众号后台通过查看元素可以看到关注者的openid
![image](https://user-images.githubusercontent.com/58971504/75089637-f78e2f00-5595-11ea-8bf6-6ce364ae006d.png)
就是这样来的

**Comment by xiaopengyaa** [comment]
> 百度看的教程，在公众号后台通过查看元素可以看到关注者的openid
> ![image](https://user-images.githubusercontent.com/58971504/75089637-f78e2f00-5595-11ea-8bf6-6ce364ae006d.png)
> 就是这样来的

你可以试试用fiddler抓包看看openId是不是和你这个方法所查看到的一样

**Comment by Drac4ry** [comment]
我用burpsuit抓了下包，如图
![image](https://user-images.githubusercontent.com/58971504/75103879-4b535380-563c-11ea-9456-a03066da8fe1.png)
这是一个获取关注者信息的post包
上面一行的openid是我每个包都会带有的（格式看不懂
下面一行是获取关注者信息才有的（我之前用F12查看到的就是这个
不知道哪一部分才是真正的openid？
或者你是怎么获取的可以指导一下么

**Comment by xiaopengyaa** [comment]
> 我用burpsuit抓了下包，如图
> ![image](https://user-images.githubusercontent.com/58971504/75103879-4b535380-563c-11ea-9456-a03066da8fe1.png)
> 这是一个获取关注者信息的post包
> 上面一行的openid是我每个包都会带有的（格式看不懂
> 下面一行是获取关注者信息才有的（我之前用F12查看到的就是这个
> 不知道哪一部分才是真正的openid？
> 或者你是怎么获取的可以指导一下么

我是使用fiddler直接抓包手机端里微信小程序的包，在小程序里登录后都会产生一个openId，你可以用这种方法试试。（怎么使用fiddler抓包你可以搜索一下）

**Comment by Drac4ry** [comment]
你好，我用了fiddler抓到了小程序的包，但是找不到有关openid的值，请问查找关键字是？
百度搜索也找不到相关的答案...全都是要用公众号接口交互获取，请问你是怎么获取的？

**Comment by xiaopengyaa** [comment]
> 你好，我用了fiddler抓到了小程序的包，但是找不到有关openid的值，请问查找关键字是？
> 百度搜索也找不到相关的答案...全都是要用公众号接口交互获取，请问你是怎么获取的？

你是使用什么手机抓的包？

**Comment by Drac4ry** [comment]
小米，这是我打开小程序过程中抓到的所有包
![image](https://user-images.githubusercontent.com/58971504/75113424-db1eef00-5688-11ea-991d-e70fd57bb508.png)

**Comment by xiaopengyaa** [comment]
> 小米，这是我打开小程序过程中抓到的所有包
> ![image](https://user-images.githubusercontent.com/58971504/75113424-db1eef00-5688-11ea-991d-e70fd57bb508.png)

你找个苹果手机试试，安卓手机微信7.0后不能抓取https数据了

**Comment by Drac4ry** [comment]
我没有苹果手机，试了几个抓包软件都没弄成，正打算把微信卸载换低版本，搞过获取openid的同学告诉我我在公众平台后台查看的id和他抓到的一样，于是就不打算装低版本了。
您也可以查看一下应该是同一个openid，现在就不知道是什么问题导致没有预约记录了...

**Comment by xiaopengyaa** [comment]
> 我没有苹果手机，试了几个抓包软件都没弄成，正打算把微信卸载换低版本，搞过获取openid的同学告诉我我在公众平台后台查看的id和他抓到的一样，于是就不打算装低版本了。
> 您也可以查看一下应该是同一个openid，现在就不知道是什么问题导致没有预约记录了...

公众号后台查看是指登录属于自己的公众号么？如果是的话，那么获取到的openId只是当前微信号所对应那个公众号的openId，并不是对应守护港城小程序的openId。

**Comment by Drac4ry** [comment]
这么说openid不是唯一的？每一个公众号都对应不同的openid，那同学帮我在他公众号获取到的openid也不适用于守护港城小程序了，是吗

**Comment by xiaopengyaa** [comment]
> 这么说openid不是唯一的？每一个公众号都对应不同的openid，那同学帮我在他公众号获取到的openid也不适用于守护港城小程序了，是吗


> 这么说openid不是唯一的？每一个公众号都对应不同的openid，那同学帮我在他公众号获取到的openid也不适用于守护港城小程序了，是吗

嗯嗯 是的

**Comment by xiaopengyaa** [comment]
> 这么说openid不是唯一的？每一个公众号都对应不同的openid，那同学帮我在他公众号获取到的openid也不适用于守护港城小程序了，是吗

嗯嗯 是的

**Comment by Drac4ry** [comment]
我终于获取到了...但是有两个，不一样的，请问大佬哪一个包的才是
![image](https://user-images.githubusercontent.com/58971504/75162709-eb9e9a80-5758-11ea-896d-80a4aa8808bb.png)

**Comment by xiaopengyaa** [comment]
> 我终于获取到了...但是有两个，不一样的，请问大佬哪一个包的才是
> ![image](https://user-images.githubusercontent.com/58971504/75162709-eb9e9a80-5758-11ea-896d-80a4aa8808bb.png)

/api/book/myBookList.action拿这个包的openId

**Comment by Drac4ry** [comment]
好，感谢大佬。我明儿试试

**Comment by xiaopengyaa** [comment]
> 好，感谢大佬。我明儿试试

成功了的话 记得给个star哟

**Comment by Drac4ry** [comment]
不用成功，现在就给，劳烦大佬了

**Comment by Drac4ry** [comment]
昨天拿到口罩了忘记和大佬说一声，再次感谢您~
不过我这儿明天开始变成预约摇号的了 (┬＿┬）
大佬可不可以看一下守护槎城这个是不是也可以用同样的方法预约，小伙伴表示他抢了两星期都抢不到已经绝望了

**Comment by xiaopengyaa** [comment]
> 昨天拿到口罩了忘记和大佬说一声，再次感谢您~
> 不过我这儿明天开始变成预约摇号的了 (┬＿┬）
> 大佬可不可以看一下守护槎城这个是不是也可以用同样的方法预约，小伙伴表示他抢了两星期都抢不到已经绝望了

你小伙伴是用的什么预约

**Comment by xiaopengyaa** [comment]
> > 昨天拿到口罩了忘记和大佬说一声，再次感谢您~
> > 不过我这儿明天开始变成预约摇号的了 (┬＿┬）
> > 大佬可不可以看一下守护槎城这个是不是也可以用同样的方法预约，小伙伴表示他抢了两星期都抢不到已经绝望了
> 
> 我去弄一下吧

已支持守护槎城小程序，具体使用方法请看README.md

**Comment by xiaopengyaa** [comment]
> 昨天拿到口罩了忘记和大佬说一声，再次感谢您~
> 不过我这儿明天开始变成预约摇号的了 (┬＿┬）
> 大佬可不可以看一下守护槎城这个是不是也可以用同样的方法预约，小伙伴表示他抢了两星期都抢不到已经绝望了

已支持守护槎城小程序，具体使用方法请看README.md

**Comment by Drac4ry** [comment]
哇大佬也太强了( ° ▽、° ) 感谢感谢♥
然后湛江的其实可以去掉了，官方说今晚0点开始启动2.0版摇号的
